import os
Print("=================Menu==============")
n=int(input("[1]-FIBERLINK [2]INFOWEB [3]ITECH [4]MEGAVIA [5] INTERATIVA TSA [6] INTERATIVA PIP) [7] COMPUNET"))
i=int(input("Nª do mês do Relatorio"))
s=int(input("Nª da semana do Relatorio"))
if n = 1:
    print("FIBERLINK")
    os.rename("(Vlanif851) sessao.fortel.v4 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_rede-fiberlink_s{s}-{i}-2021.pdf")
    os.rename("(Vlanif852) sessao.fortel.v6 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv6_rede-fiberlink_s{s}-{i}-2021.pdf")
    os.rename("GGC _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_v6_cdn_ggc_rede-fiberlink_s{s}-{i}-2021.pdf")
    os.rename("(port-channel1) Lagg20G-NETFLIX 20 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_v6_cdn_nfx_rede-fiberlink_s{s}-{i}-2021.pdf")
    os.rename("(port-channel3) Lagg40G-FACEBOOK 40 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_v6_cdn_fna_rede-fiberlink_s{s}-{i}-2021.pdf")
    os.rename("(Vlanif297) cli-franweb-altos 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_cdn_fwb_rede-fiberlink_s{s}-08-2021.pdf")
    os.rename("(et-0_0_0.96) EBGP-FIBERLINK 40 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_ix-ora_rede-fiberlink_s{s}-{i}-2021.pdf")
if n = 2:
    print("INFOWEB")
    os.rename("(et-0_0_0.1111) EBGP-IPV4-WIRELINK 40 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_rede-infoweb_s{s}-{i}-2021.pdf")
    os.rename("(et-0_0_0.1112) EBGP-IPV6-WIRELINK 40 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv6_rede-infoweb_s{s}-{i}-2021.pdf")
    os.rename("(ae2.1295) EBGP-GOOGLE 70 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_v6_cdn_ggc01_rede-infoweb_s{s}-{i}-2021.pdf")
    os.rename("(ae2.1296) EBGP-GOOGLE-2 70 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_v6_cdn_ggc02_rede-infoweb_s01-08-2021.pdf")
    os.rename("(ae2.1294) EBGP-NETFLIX 70 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_v6_cdn_nfx_rede-infoweb_s{s}-{i}-2021.pdf")
    os.rename("(ae2.1000) EBGP-FACEBOOK 70 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_v6_cdn_fna_rede-infoweb_s{s}-{i}-2021.pdf")
    os.rename("(lt-0_0_0.7) IX-ORA-ROUTER-MASTER-IPV4 100 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_ix_ora_rede-infoweb_s{s}-{i}-2021.pdf")
    os.rename("(lt-0_0_0.9) IX-ORA-ROUTER-MASTER-IPV6 100 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv6_ix_ora_rede-infoweb_s{s}-{i}-2021.pdf")
    os.rename("(et-0_0_0.1008) EBGP-IPV4-IX-THE 40 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_ix_tsa_rede-infoweb_s{s}-{i}-2021.pdf")
    os.rename("(et-0_0_0.1009) EBGP-IPV6-IX-THE 40 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv6_ix_tsa_rede-infoweb_s{s}-{i}-2021.pdf")
    os.rename("(ae2.2012) EBGP-IPV4-IX-SLZ 70 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_ix_slz_rede-infoweb_s{s}-{i}-2021.pdf")
    os.rename("(ae2.2013) EBGP-IPV6-IX-SLZ 70 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv6_ix_slz_rede-infoweb_s{s}-{i}-2021.pdf")
if n = 3:
    print("ITECH")
    os.rename("(Vlanif62) link-wlk-ipv4 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_rede-itech_s{s}-{i}-2021.pdf")
    os.rename("(Vlanif63) link-wlk-ipv6 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv6_rede-itech_{s}-{i}-2021.pdf")
    os.rename("(Vlanif630) Uplink-Parnarama-via-amarante 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_rede-itech-amarante_s{s}-{i}-2021.pdf")
    os.rename("(Vlanif154) ggc 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4-v6-cdn-ggc_rede-itech_s{s}-{i}-2021.pdf")
    os.rename("(Vlanif153) netflix 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4-v6-cdn-nfx_rede-itech_s{s}-{i}-2021.pdf")
    os.rename("(Vlanif155) fna 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4-v6-cdn-fna_rede-itech_s{s}-{i}-2021.pdf")
    os.rename("(et-0_0_0.227) EBGP-ITECH 40 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4-ix-ora_rede-itech-amarante_s01-08-2021")
if n = 4:
    print("MEGAVIA")
    os.rename("(Vlanif2034) sessao-bgp-wirelink 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_v6_rede-megavia_s{s}-{i}-2021.pdf")
    os.rename("(Vlanif2036) Sessao-Wirelink-IPv6 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv6_rede-megavia_s{s}-{i}-2021.pdf")
    os.rename("(et-0_0_0.229) EBGP-MEGAVIA 40 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4-ix-ora_rede-megavia-s{s}-{i}-2021.pdf")
if n = 5:
    print("INTERATIVA TSA")
    os.rename("(Vlanif641) LINK-IPv4-WIRELINK 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_rede-interativa-tsa_s{s}-{i}-2021.pdf")
    os.rename("(Vlanif642) LINK-IPv6-WIRELINK 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv6_rede-interativa-tsa_s{s}-{i}-2021.pdf")
    os.rename("(Vlanif100) Servidores CDN GGC 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","")
    os.rename("relatorio_link-ipv4-v6-cdn-ggc_rede-interativa-tsa_s01-08-2021","relatorio_link-ipv4-v6-cdn-ggc_rede-interativa-tsa_s{s}-{8}-2021.pdf")
    os.rename("(Eth-Trunk8) LAGG-20G-SERVIDOR-NETFLIX-INTERATIVA 20 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4-v6-cdn-nfx_rede-interativa-tsa_s{s}-{8}-2021.pdf")
    os.rename("(et-0_0_0.228) EBGP-INTERATIVA 40 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4-ix-ora_rede-interativa-tsa_s{s}-{i}-2021.pdf")
if n = 6:
    print("INTERATIVA PIP")
    os.rename("(Vlanif70) cli-ora-telecom-ipv4 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_rede-interativa-pip_s{s}-{i}-2021.pdf")
    os.rename("(Vlanif72) cli-ora-telecom-ipv6 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv6_rede-interativa-pip_s{s}-{i}-2021.pdf")
    os.rename("(et-0_0_0.193) EBGP-INTERATIVA-PIP-IPv6 40 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv6-ix-ora_rede-interativa-pip_s01-08-2021")
if n = 7:
    print("COMPUNET")
    os.rename("(Vlanif59) cli.bonfimesoualtda.iptransito.as264991(cliente da infoweb) 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4_rede-compunet_s{s}-{i}-2021.pdf")
    os.rename("(Vlanif60) cli.bonfimesoualtda.ipt.v6.as264991(cliente da infoweb) 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv6_rede-compunet_s{s}-{i}-2021.pdf")
    os.rename("(Vlanif61) cli.bonfimesousa.cdn.as264991(cliente infoweb) 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv4-cdn_rede-compunet_s{s}-{i}-2021.pdf")
    os.rename("(Vlanif62) cli.bonfimesousa.cdnv6.as264991(cliente infoweb) 1 GBit_s _ Relatório _ PRTG - NOC Ora Telecom.pdf","relatorio_link-ipv6-cdn_rede-compunet_s{s}-{i}-2021.pdf")


    
